server:
  port: ${ELECTION_API_PORT}

spring:
  application:
    name: ElectionAPI
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${ELECTION_API_DB_URL}
    username: ${ELECTION_API_DB_USERNAME}
    password: ${ELECTION_API_DB_PASSWORD}
